### PR TITLE
adding arabic language

### PR DESCRIPTION
**Pull request by jamal-alnaeb**

### CODE REVIEW

**Review by decryp2kanon — APPROVED** [review]
thanks!

**Comment by decryp2kanon** [comment]
@jamal-alnaeb pls write here your sugar address

**Comment by jamal-alnaeb** [comment]
Good morning.
here is my sugar address sugar1qj3qnldxz33z47ggt85knkmvxtw6fa8xsynr3sr
Thank you

**Comment by decryp2kanon** [comment]
@AestheticSenpai yeah can you reward him?
`sugar1qj3qnldxz33z47ggt85knkmvxtw6fa8xsynr3sr`

**Comment by AestheticSenpai** [comment]
👍

**Pull request merged**
